//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeDeflautBox.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WriteCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WriteCode() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeDeflautBox.Properties.WriteCode", typeof(WriteCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///
        ///namespace program
        ///{
        ///	class Program
        ///	{
        ///		public static void Main()
        ///		{
        ///			Console.WriteLine(&quot;Hello world!&quot;);
        ///			Console.ReadKey();
        ///		}
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///
        ///namespace program
        ///{
        ///	class Program
        ///	{
        ///		public static void Main()
        ///		{
        ///			System.Windows.Forms.MessageBox.Show(&quot;Hello World!&quot;);//要引用Windows.Forms
        ///		}
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        public static string MessageBox {
            get {
                return ResourceManager.GetString("MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///
        ///namespace program
        ///{
        ///	class Program
        ///	{
        ///		public static void Main()
        ///		{
        ///			int a = 10, b = 20;
        ///			Console.WriteLine($&quot;a = {a}&quot;);
        ///			Console.WriteLine($&quot;b = {b}&quot;);
        ///			Console.WriteLine($&quot;a + b = {a + b}&quot;);
        ///			Consolr.ReadKey();
        ///		}
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        public static string OperatorVar {
            get {
                return ResourceManager.GetString("OperatorVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///
        ///namespace program
        ///{
        ///	class Program
        ///	{
        ///		public static void Main()
        ///		{
        ///			int a = 0, b = 0;
        ///			Console.WriteLine($&quot;a = {a}\nb = {b}&quot;);
        ///			a = 10, b = 20;
        ///			Console.WriteLine($&quot;a = {a}\nb = {b}&quot;);
        ///			Console.WriteLine($&quot;a + b = {a + b}&quot;);
        ///			Console.ReadKey();
        ///		}
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        public static string SetVar {
            get {
                return ResourceManager.GetString("SetVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
